name: hyperbolic_duo
backbone: dit
parameterization: mean
time_conditioning: True
T: 0
subs_masking: False
causal_attention: False
ignore_bos: False
loss_type: elbo

# Hyperbolic diffusion parameters
trainset_path: /share/thickstun/sychou/workspace/research/duo/hyper_dataset/word_embedding/trainset_gpt2_wikitext2_ml256_bs32.pt
noise_euler_steps: 128
lamb_factor: 0.25
lamb_decay_exp: 0.05
